=== MatousJobanek/PB138-XML-Exercises/xmlExercisesFiles/dtd/company/solution.dtd
<!ELEMENT company (employee*)>
<!ELEMENT employee (name, salary_per_hour, salary_daily, importance)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary_per_hour (#PCDATA)>
<!ELEMENT salary_daily (#PCDATA)>
<!ELEMENT importance (#PCDATA)>
<!ATTLIST employee shift CDATA #REQUIRED>
<!ATTLIST salary_daily earned (true|false) #IMPLIED>

=== MatousJobanek/PB138-XML-Exercises/xmlExercisesFiles/dtd/company/data4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "solution.dtd">
<company>
  <employee shift="8">
    <name>Bob</name>
    <salary_per_hour>8.00</salary_per_hour>
    <salary_daily earned="true">64.00</salary_daily>
    <importance>low</importance>
  </employee>
  <employee shift="4">
    <name>Alice</name>
    <salary_per_hour>6.00</salary_per_hour>
    <salary_daily>24.00</salary_daily>
    <importance>medium</importance>
  </employee >
  <employee shift="8">
    <name>Dylan</name>
    <salary_per_hour>15.00</salary_per_hour>
    <salary_daily earned="false">120.00</salary_daily>
    <importance>medium</importance>
  </employee>
  <employee shift="5">
    <name>Katia</name>
    <salary_per_hour>24.00</salary_per_hour>
    <salary_daily>120.00</salary_daily>
    <importance>high</importance>
  </employee>
  <employee shift="">
    <name>Chris</name>
    <salary_per_hour>13.50</salary_per_hour>
    <salary_daily earned="true">108.00</salary_daily>
    <importance>high</importance>
  </employee>
</company>
