=== MatousJobanek/PB138-XML-Exercises/xmlExercisesFiles/dtd/articles/solution.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ARTICLES (ARTICLE*)>
<!ELEMENT ARTICLE (ARTICLEDATA*)>
<!ELEMENT ARTICLEDATA (TITLE,AUTHOR)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>

=== MatousJobanek/PB138-XML-Exercises/xmlExercisesFiles/dtd/articles/data1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ARTICLES SYSTEM "solution.dtd">
<ARTICLES>
  <ARTICLE>
    <ARTICLEDATA>
      <TITLE>XML Demystified</TITLE>
      <AUTHOR>Jaidev</AUTHOR>
    </ARTICLEDATA>
  </ARTICLE>
  <ARTICLE>
    <ARTICLEDATA>
      <TITLE>Hardcore Hardware</TITLE>
      <AUTHOR>Janett</AUTHOR>
    </ARTICLEDATA>
  </ARTICLE>
  <ARTICLE>
    <ARTICLEDATA>
      <TITLE>Cooking for Dummies</TITLE>
      <AUTHOR>Tobias Cook</AUTHOR>
    </ARTICLEDATA>
  </ARTICLE>
  <ARTICLE>
    <ARTICLEDATA>
      <TITLE>Feminism basics</TITLE>
      <AUTHOR>Julia Roscow</AUTHOR>
    </ARTICLEDATA>
    <ARTICLEDATA>
      <TITLE>Strong women among us</TITLE>
      <AUTHOR>Catherine Smith</AUTHOR>
    </ARTICLEDATA>
  </ARTICLE>
</ARTICLES>
